# Generated by Django 6.0.2 on 2026-02-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=100, verbose_name='Nome Exercício')),
                ('grupoMuscular', models.CharField(choices=[('PEITO', 'Peito'), ('COSTAS', 'Costas'), ('PERNAS', 'Pernas'), ('BRACOS', 'Braços'), ('OMBROS', 'Ombros')], default='PEITO', max_length=20)),
                ('carga', models.IntegerField(default=1, help_text='Carga em Kg')),
                ('series', models.PositiveIntegerField(verbose_name='Séries')),
                ('repeticoes', models.PositiveIntegerField(verbose_name='Repetições')),
                ('dataTreino', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-dataTreino'],
            },
        ),
    ]
