# Generated by Django 6.0.2 on 2026-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotreino',
            name='carga',
            field=models.DecimalField(decimal_places=1, help_text='Carga em Kg', max_digits=5),
        ),
    ]
