# Generated by Django 6.0.2 on 2026-03-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0003_registrotreino_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotreino',
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
