# Generated by Django 6.0.2 on 2026-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0004_rename_usuarios_registrotreino_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrotreino',
            options={'ordering': ['dia_semana']},
        ),
        migrations.RemoveField(
            model_name='registrotreino',
            name='dataTreino',
        ),
        migrations.AddField(
            model_name='registrotreino',
            name='dia_semana',
            field=models.CharField(choices=[('1_SEG', 'Segunda-feira'), ('2_TER', 'Terça-feira'), ('3_QUA', 'Quarta-feira'), ('4_QUI', 'Quinta-feira'), ('5_SEX', 'Sexta-feira'), ('6_SAB', 'Sábado'), ('7_DOM', 'Domingo')], default='1_SEG', max_length=5, verbose_name='Dia da Semana'),
        ),
    ]
